# Generated by Django 3.0.2 on 2020-03-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='pics/accounts'),
        ),
    ]
