# Generated by Django 3.0.2 on 2020-02-24 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200225_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='register',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='register.register'),
            preserve_default=False,
        ),
    ]
