# Generated by Django 3.0.2 on 2020-03-26 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200327_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='displaypicture',
            new_name='img',
        ),
    ]
