# Generated by Django 3.0.4 on 2020-04-01 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_eventsregistered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsregistered',
            name='eventsregistered',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
