# Generated by Django 3.0.4 on 2020-04-01 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200402_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsregistered',
            name='eventsregistered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
