# Generated by Django 3.0.4 on 2020-04-01 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200402_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredevent',
            name='registeredevent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
