# Generated by Django 3.0.4 on 2020-04-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200402_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredevent',
            name='eventid',
            field=models.IntegerField(),
        ),
    ]
