# Generated by Django 3.0.4 on 2020-04-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200402_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredevent',
            name='eventid',
            field=models.CharField(max_length=50),
        ),
    ]
