# Generated by Django 3.0.4 on 2020-04-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_newuserregisterevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuserregisterevent',
            name='username',
        ),
    ]
