# Generated by Django 3.0.2 on 2020-03-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200318_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='url',
            new_name='slug',
        ),
    ]
