# Generated by Django 3.0.2 on 2020-03-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200318_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(default='name-date(01012001)', max_length=50),
        ),
    ]
