# Generated by Django 3.0.2 on 2020-03-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200318_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(default='name%place%01%01%2001%', max_length=50),
        ),
    ]
